mjm-sgcorp/SGCorp/SGCorp.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SGCorp.BLL;
using SGCorp.Models;
using SGCorp.Models.Models;

namespace SGCorp.UI.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddApplication()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddApplication(Applicant applicant)
        {
            if (ModelState.IsValid)
            {
                var manager = new ApplicantManager();

                manager.AddApplicant(applicant);
                return View("AddApplicationConfirm");
            }
            return View(applicant);

        }

        public ActionResult AddApplicationConfirm()
        {
            return View();
        }

        public ActionResult ViewApplicants()
        {
            var manager = new ApplicantManager();
            var list = manager.GetAllApplicants();
            
            return View(list.Data);
        }

        public ActionResult ViewSingleApplicant(int id)
        {
            var manager = new ApplicantManager();
            var applicant = manager.GetSingleApplicant(id);

            return View(applicant.Data);

        }
    }
}

mjm-sgcorp/SGCorp/SGCorp.UI/Controllers/PolicyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SGCorp.BLL;
using SGCorp.Models.Models;

namespace SGCorp.UI.Controllers
{
    public class PolicyController : Controller
    {
        //public ActionResult ViewPolicies(Category category)
        //{
        // return View(category.Policies);
        //}

        public ActionResult ViewPolicies()
        {
            PolicyManager manager = new PolicyManager();
            var categories = manager.GetAllCategories();

            return View(categories);
        }

        public ActionResult ManagePolicies()
        {
            PolicyManager manager = new PolicyManager();
            var categories = manager.GetAllCategories();

            return View(categories);
        }

        public ActionResult ManageCategories()
        {
            PolicyManager manager = new PolicyManager();
            var categories = manager.GetAllCategories();

            return View(categories);
        }

        public ActionResult ViewPolicyTable(int id)
        {
            PolicyManager manager = new PolicyManager();
            var category = manager.GetByID(id);
            return View(category);
        }

        public ActionResult DeletePolicy(Policy policy)
        {
            PolicyManager manager = new PolicyManager();
            manager.DeletePolicy(policy);

            return RedirectToAction("ManagePolicies");
        }

        public ActionResult DeleteCategory(Category category)
        {
            PolicyManager manager = new PolicyManager();
            manager.DeleteCategory(category.CategoryId);

            return RedirectToAction("ManageCategories");
        }


        public ActionResult EditPolicy(Policy policy)
        {
            return View(policy);
        }

        [HttpPost]
        public ActionResult SaveEditPolicy(Policy policy)
        {

            var manager = new PolicyManager();

            manager.EditPolicy(policy);
            return RedirectToAction("ManagePolicies");
        }

        public ActionResult AddPolicy()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddPolicy(Policy policy)
        {
            var manager = new PolicyManager();
            if (ModelState.IsValid)
            {
                manager.AddPolicy(policy);
                return RedirectToAction("ManagePolicies");
            }
            return View(policy);
        }

        //public ActionResult ManageCategories()
        //{

            //    return View();
            //}

        public ActionResult ViewSinglePolicy(string descrpition)
        {
           return View(descrpition);
        }
    }
}

mjm-sgcorp/SGCorp/SGCorp.UI/Controllers/TimeEntryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SGCorp.BLL;
using SGCorp.Models.Models;

namespace SGCorp.UI.Controllers
{
    public class TimeEntryController : Controller
    {
        public ActionResult SubmitTime()
        {
            EmployeeManager manager = new EmployeeManager();
            ViewBag.Employees = manager.GetAllEmployees();
            return View();
        }

        public ActionResult ViewTimeSheet()
        {
            EmployeeManager manager = new EmployeeManager();
            var employees = manager.GetAllEmployees();

            return View(employees);
        }


        [HttpPost]
        public ActionResult SubmitTime(TimeEntry time )
        {
            EmployeeManager manager = new EmployeeManager();
            manager.AddTime(time);

            return RedirectToAction("ViewTimeSheet");
        }

        public ActionResult ViewEmployeeTime(int id)
        {
            EmployeeManager manager = new EmployeeManager();
            var emp = manager.GetEmpByID(id);
            return View(emp);
        }
        public ActionResult DeleteTime(TimeEntry entry)
        {
            EmployeeManager manager = new EmployeeManager();
            manager.DeleteTime(entry);

            return RedirectToAction("ViewEmployeeTime", new {id = entry.EmpId});
        }
    }
}

mjm-sgcorp/SGCorp/SGCorp.UI/Views/Policy/AddPolicy.cshtml
@model SGCorp.Models.Models.Policy
@{
    ViewBag.Title = "AddPolicy";
}

<h2>Add New Policy</h2>

@using (Html.BeginForm())
{
    <table>
        <tr>
            <td>Category Name: </td>
            <td>@Html.TextBoxFor(m => m.CategoryName, new {@class="form-control", data_validation="required", data_validation_error_msg="Enter a category"})</td>
        </tr>
        <tr>
            <td>Policy Name: </td>
            <td>@Html.TextBoxFor(m => m.PolicyName, new { @class = "form-control", data_validation = "required", data_validation_error_msg = "Enter a policy name" })</td>
        </tr>
        <tr>
            <td>Policy Description: </td>
            <td>@Html.TextAreaFor(m => m.Description, 10, 80, new { @class = "form-control", data_validation = "required", data_validation_error_msg = "Enter a description" })</td>
        </tr>
    </table>
    <button class="btn btn-success center-block">Save</button>
    <div style="padding-top: 20px"></div>
}


@section scripts{

    <script>

        $.validate({
            modules: 'html5',
            borderColorOnError: '#FFF',
            addValidClassOnAll: true,
            scrollToTopOnError: true
        });

    </script>

}

mjm-sgcorp/SGCorp/SGCorp.UI/Views/Policy/EditPolicy.cshtml
@model SGCorp.Models.Models.Policy
@{
    ViewBag.Title = "EditPolicy";
}
<style>
    #content {
        border: 2px solid maroon;
        border-radius: 10px;
        padding-top: 20px;
        padding-bottom: 20px;
            
    }
</style>
@using (Html.BeginForm("SaveEditPolicy","Policy",FormMethod.Post))
{

    <h2>Edit Policy</h2>
    <div id="content" class="center-block">
        @Html.HiddenFor(m => m.CategoryName)
        @Html.HiddenFor(m => m.PolicyName)
        @Html.TextAreaFor(m => m.Description, 10, 80, new {@class="form-control center-block"})
        <div style="padding-top: 20px"></div>
        <button class="btn btn-success center-block">Save</button>
    </div>
    <div style="padding-top: 20px"></div>
}

mjm-sgcorp/SGCorp/SGCorp.UI/Views/Policy/ManageCategories.cshtml
@model List<SGCorp.Models.Models.Category>
@{
    ViewBag.Title = "ManageCategories";
}
<style>
    h2 {
        font-family: serif;
        color: maroon;
        text-align: center;
    }
    tr td:first-child {
        font-family: serif;
        color: maroon;
        font-size: 20px
    }
    .list-group {
        max-width: 500px;

    }
    .list-group-item {
        min-height: 50px;
    }
    .content {
        display: block;
        min-height: 700px;
    }
</style>
<h2>Manage Categories</h2>
<div class="content">
    <ul class="list-group">
        @foreach (var category in Model)
        {

            <li class="list-group-item"> @category.CategoryName @Html.ActionLink("Delete", "DeleteCategory", "Policy", @category, new { @class = "btn btn-danger pull-right" }) </li>

        }
    </ul>
</div>
    

mjm-sgcorp/SGCorp/SGCorp.UI/Views/Policy/ManagePolicies.cshtml
@model List<SGCorp.Models.Models.Category>
@{
    ViewBag.Title = "Manage Policies";
}
<style>
    h2 {
        text-align: center;
        color: maroon;
        font-family: serif;
    }

    #content {
        border-radius: 10px;
        border: 2px solid maroon;
        max-width: 500px;
        min-height: 400px;
        text-align: center;
    }

    .dropdown{
        margin: auto;
        display: block;
        text-align: center;
    }
 
</style>
<h2>Manage Policies</h2>
<div class="center-block" id="content">
    <div style="padding-bottom: 50px"></div>

    <div class="dropdown" style="text-align: center">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            Select Category
            <span class="caret"></span>
        </button>

        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1" >
            @foreach (var category in Model)
            {
                <li>@Html.ActionLink(@category.CategoryName, "ViewPolicyTable", "Policy", new { id = @category.CategoryId }, null)</li>
            }
        </ul>

    </div>
    <div style="padding-bottom: 150px"></div>
    <div style="text-align: center">
        @Html.ActionLink("Add Policy", "AddPolicy", "Policy", null, new { @class = "btn btn-success" })
    </div>
</div>


<div style="padding-bottom: 50px"></div>

mjm-sgcorp/SGCorp/SGCorp.UI/Views/Policy/ViewCategory.cshtml
@model List<string>

@{
    ViewBag.Title = "Categories";
}

<h2>Categories</h2>

<tbody>
    @foreach (var category in Model)
    {
        <tr>
            <td>@Html.ActionLink(@category, "ViewPolicies", "Policy", new { @category }, null)</td>
        </tr>
    }
</tbody>

mjm-sgcorp/SGCorp/SGCorp.UI/Views/Policy/ViewPolicies.cshtml
@model List<SGCorp.Models.Models.Category>
@{
    ViewBag.Title = "ViewPolicies";
}

<style>
    h2 {
        text-align: center;
    }

    th, td {
        padding-left: 50px;
    }

    .whitearea {
        min-height: 450px;
    }

    a {
        color: white;
        text-decoration: none;
    }
     a:visited {
        color: white;
        text-decoration: none;
    }
    a:hover {
        color: orange;
        text-decoration: none;
    }
    a:active  {
        color: white;
        text-decoration: none;
    }
    .policyName {
        font-family: serif;
        color: maroon;
        font-size: 20px;
        text-decoration: underline;
    }
</style>

<h2>SG Corp Policies</h2>

<div class="whitearea">

    @foreach (var category in Model)
    {
        <div class="panel panel-default">
            <div class="panel-heading"style="max-height: 40px">
                <a data-toggle="collapse" href="@("#collapse" + category.CategoryId)"><h5>@category.CategoryName</h5></a>
            </div>
            <div id="@("collapse" + category.CategoryId)" class="panel-collapse collapse">
                @foreach (var policy in category.Policies)
                {
                    <div class="panel-body">
                        <div class="policyName">@policy.PolicyName</div>
                        @policy.Description
                    </div>
                }
            </div>
            </div>
    }
</div>

mjm-sgcorp/SGCorp/SGCorp.UI/Views/Policy/ViewPolicyTable.cshtml
@model SGCorp.Models.Models.Category
@{
    ViewBag.Title = "ViewPolicyTable";
}

<h2>ViewPolicyTable</h2>
<table>
    
    @foreach (var policy in Model.Policies)
    {
        <tr>
            <td>@policy.PolicyName</td>
            <td>@Html.ActionLink("Edit", "EditPolicy", "Policy", @policy, new { @class = "btn btn-primary" })</td>
            <td>@Html.ActionLink("Delete", "DeletePolicy", "Policy", @policy, new { @class = "btn btn-primary" })</td>
        </tr>
    }
</table>

mjm-sgcorp/SGCorp/SGCorp.UI/Views/Policy/ViewSinglePolicy.cshtml
@model string
@{
    ViewBag.Title = "ViewSinglePolicy";
}

<h2>ViewSinglePolicy</h2>
<p>@Model</p>

mjm-sgcorp/SGCorp/SGCorp.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="/Images/favicon.ico">
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("SG Corp.", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
                <a href="~/Home/Index"><img src="/Images/swg_logo-white.png" alt="SG" height="50" width="50"></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li></li>
                    <li>@Html.ActionLink("View Applicants", "ViewApplicants", "Home", new { area = "" }, null)</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-book"></span> Policies<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("View Policies", "ViewPolicies", "Policy", new {area = ""}, null)</li>
                            <li>@Html.ActionLink("Manage Policies", "ManagePolicies", "Policy", new {area = ""}, null)</li>
                            <li>@Html.ActionLink("Manage Categoies", "ManageCategories", "Policy", new {area = ""}, null)</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-time"></span> Time Tracking<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Submit Time", "SubmitTime", "TimeEntry", new { area = "" }, null)</li>
                            <li>@Html.ActionLink("View Timesheet", "ViewTimeSheet", "TimeEntry", new { area = "" }, null)</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">

        @RenderBody()

    </div>
    <div>
        <footer>
            <p>&copy; @DateTime.Now.Year - SG Corp.</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.2.8/jquery.form-validator.min.js"></script>
    @RenderSection("scripts", false)
</body>
</html>

mjm-sgcorp/SGCorp/SGCorp.UI/Views/Shared/_LayoutApplication.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="/Images/favicon.ico">
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css"/>
    <link href="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.2.8/theme-default.min.css"
          rel="stylesheet" type="text/css" />
    <style>
        .body-content {
            max-width: 800px;
        }
    </style>
</head>
<body>
    <div class="container body-content">

        @RenderBody()

    </div>

<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/scripts/jquery-1.12.0.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.2.8/jquery.form-validator.min.js"></script>
    @RenderSection("scripts", false)
</body>
</html>